### ISSUE TITLE
dbEnsure is not a function

### ISSUE THREAD

**Issue by hotsu0p** [Tomato6966/Multipurpose-discord-bot#205] opened 2023-10-30 18:37 UTC
## **What's your nodejs Version.**
>v16.13.2

## **What's the version you downloaded the bot?**
>Latest

## **Desktop (please complete the following information):**
> - OS:luinix
> - Version 20.24

## **Describe the bug**
> === UNHANDLED REJECTION ===

Reason:  TypeError: dbEnsure is not a function

## **To Reproduce**
> Steps to reproduce the behavior e.g:
1. Click the button on the command setup-apply
2. See the error in the console

## **Expected behavior**
> For the apply system to work

## **Additional context, text and screenshots!**
>Nope

**Comment by M3rcena** [comment] 2023-12-26 16:56
Hello @hotsu0p,

I just checked the bot, it seems that I cannot reproduce the problem, is it still active?

**Comment by hotsu0p** [comment] 2023-12-26 19:13
Nope @Tomato6966 got it fixed in another version of the bot

**Comment by M3rcena** [comment] 2023-12-26 19:15
Perfect! can you please close this request? I am trying to check everything.

**Comment by hotsu0p** [comment] 2023-12-26 19:16
Wait
i just remmberd the code for the setup-apply code doesnt work

**Comment by hotsu0p** [comment] 2023-12-26 19:16
and this is what that was about

**Comment by M3rcena** [comment] 2023-12-26 19:18
Well the command workes just fine! I just tested it

**Comment by hotsu0p** [comment] 2023-12-26 19:19
how? the code from here doesnt when you clikc the apply button

**Comment by M3rcena** [comment] 2023-12-26 19:20
oh you didn't mention the apply button, I thought the starting button of the command. Allow me a minute to test it and if it has an error it will be fixed!

**Comment by vuthanhtrung2010** [comment] 2024-01-12 13:25
Because of emojis, Please replace the emojis or just add it to milrato!

**Comment by M3rcena** [comment] 2024-01-12 13:27
> Because of emojis, Please replace the emojis or just add it to milrato!

Yes, I have located the issue already and it's fixed!

**Comment by hotsu0p** [comment] 2024-01-12 13:41
You fixed it?

**Comment by M3rcena** [comment] 2024-01-12 13:42
> You fixed it?

Yes but it's not uploaded yet! I am remodelling the whole bot to mjs

**Comment by hotsu0p** [comment] 2024-01-12 13:43
whats mjs?

**Comment by M3rcena** [comment] 2024-01-12 13:43
> whats mjs?
> 

It's Module JavaScript!

**Comment by hotsu0p** [comment] 2024-01-12 13:44
Oh alr

**Comment by M3rcena** [comment] 2024-01-12 13:44
> Oh alr

After updating the whole bot it will most likely be uploaded... We will decide!

**Closed** 2024-04-12 18:30 UTC
Labels: bug
